name: Build Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout using PAT
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.token }}
          persist-credentials: false
      - name: Configure Git to use PAT
        run: |
          git config --global user.name "migration-bot"
          git config --global user.email "migration-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/${{ github.repository }}.git
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean verify
      - name: Run OpenRewrite
        with:
          base: main
        run: mvn -U org.openrewrite.maven:rewrite-maven-plugin:run
      - name: Run OpenRewrite
        with:
          base: main
        run: mvn -B rewrite:run
      - name: Remove build artifacts
        run: |
          rm -rf target
          git clean -fdX  
          
      # ðŸ”´ THIS STEP CREATES THE PR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.token }}
          commit-message: "Auto-migrate Java 8 â†’ 11 (Add JAXB + fixes)"
          title: "Java 17 Migration (Automated)"
          body: |
            This PR was automatically generated by OpenRewrite.
            - Added JAXB dependencies
            - Updated Java compatibility
          branch: rewrite/java11-migration
          delete-branch: true
